name: Release CI

on:
  release:
    types: [ published ]  
  workflow_dispatch:

jobs:
  publish-npm:
    
    permissions:
      contents: write
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set version from tag
        run: |
          TAG=${GITHUB_REF##*/}
          VERSION=${TAG#v}
          echo "Setting version to $VERSION"
          npm version --no-git-tag-version "$VERSION"

      - name: Commit updated version
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -am "chore: set version to ${VERSION} from tag ${TAG}"
          git push origin HEAD:master
        env:
          TAG: ${{ github.ref_name }}
          VERSION: ${{ github.ref_name }}

      - uses: ./.github/actions/main

      - run: npm run test

      - run: npm run build

      - run: npm run docs || true

      - name: Disable Jekyll
        run: echo > docs/.nojekyll

      - name: Deploy to openglobus.github.io
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY : ${{ secrets.SSH_DEPLOY_KEY  }}
        with:
          source-directory: docs
          destination-github-username: openglobus
          destination-repository-name: openglobus.github.io
          user-name: Github Bot
          user-email: github-actions[bot]@users.noreply.github.com
          target-branch: master
          target-directory: docs

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
