name: Release CI

on:
  release:
    types: [ published ]  
  workflow_dispatch:

jobs:
  publish-npm:
    
    permissions:
      contents: write
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.repository.default_branch }}

      - name: Update package.json with release tag
        run: |
          TAG="${{ github.event.release.tag_name }}"
          echo "Updating package.json version to $TAG"
          npm version "$TAG" --no-git-tag-version

      - name: Commit and push version update
        run: |
          TAG="${{ github.event.release.tag_name }}"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add package.json package-lock.json
          git commit -m "Update package.json to version $TAG"
          git push origin ${{ github.event.repository.default_branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/main

      - run: npm run test

      - run: npm run build

      - run: npm run docs || true

      - name: Disable Jekyll
        run: echo > docs/.nojekyll

      - name: Deploy to openglobus.github.io
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY : ${{ secrets.SSH_DEPLOY_KEY  }}
        with:
          source-directory: docs
          destination-github-username: openglobus
          destination-repository-name: openglobus.github.io
          user-name: Github Bot
          user-email: github-actions[bot]@users.noreply.github.com
          target-branch: master
          target-directory: docs

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
